# Generated by Django 4.2.2 on 2023-07-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('crime_rate', models.FloatField()),
                ('safety_rate', models.FloatField()),
            ],
        ),
    ]
