# Generated by Django 4.2.2 on 2023-07-24 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_stats', '0002_crimedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
