# Generated by Django 4.2.2 on 2023-07-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_stats', '0004_reports_seriestype_countryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomicidePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HomicideRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('homicide_rate', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='countryinfo',
            name='series',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.RenameModel(
            old_name='SeriesType',
            new_name='Country',
        ),
        migrations.DeleteModel(
            name='CountryInfo',
        ),
        migrations.AddField(
            model_name='homiciderate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_stats.country'),
        ),
        migrations.AddField(
            model_name='homicidepercentage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_stats.country'),
        ),
    ]
