# Generated by Django 4.2.2 on 2023-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_stats', '0005_homicidepercentage_homiciderate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicidepercentage',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='chart_images/'),
        ),
    ]
